<?php 
//Gk USH GANTI COPYRIGHT YE ANJING
//Fitur: Extrap Kode License HMA!
//Author: ZeroSvn || BabbyCyberTeam
@ini_set('output_buffering',0);
$dasar = '-';
function GeneRate($qtd){ 
$karakter = 'ABCDEFGHIJKLMOPQRSTUVXWYZ0123456789'; 
$tykung = strlen($karakter); 
$tykung--; 

$Hash=NULL; 
    for($x=0;$x<=$qtd;$x++){ 
        $Posicao = rand(0,$tykung); 
        $Hash .= substr($karakter,$Posicao,1); 
    } 

return $Hash; 
} 
print "[ Extrap License Kode HMA! Pro Vpn ]\n";
print "Author: zerosvn@merahputih.id\n";
print "Suport By : BabbyCyberTeam || SGB-Team\n";
print "\n";

echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
echo GeneRate(5); ;
echo "$dasar"; echo GeneRate(5);
echo "$dasar"; echo GeneRate(5);
print "\n";
?>
